sonar.organization=pearl-essence
sonar.projectKey=Pearl-Essence_pearls_file_tools
sonar.projectName=Pearl Post Suite

sonar.sources=.
sonar.exclusions=tests/**,**/pearl_stress_test/**,resources/icons/**,**/__pycache__/**
sonar.tests=tests
sonar.test.inclusions=tests/**

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.10
