"""QC report generation for Pearl's File Tools.

Generates a self-contained HTML report using Python's string.Template.
Optionally extracts first-frame thumbnails via ffmpeg when available.
"""

import datetime
import shutil
import subprocess
import tempfile
from pathlib import Path
from string import Template
from typing import Optional

from constants import VIDEO_EXTENSIONS

try:
    _HAS_FFMPEG = shutil.which('ffmpeg') is not None
except Exception:
    _HAS_FFMPEG = False


# ─────────────────────────────────────────────────────────────────────────────
# Thumbnail extraction
# ─────────────────────────────────────────────────────────────────────────────

def _extract_thumbnail_b64(filepath: Path, tmp_dir: Path) -> Optional[str]:
    """Return a base-64-encoded JPEG of the first frame, or None on failure."""
    if not _HAS_FFMPEG:
        return None
    out = tmp_dir / f"{filepath.stem}_thumb.jpg"
    try:
        subprocess.run(
            ['ffmpeg', '-y', '-ss', '0', '-i', str(filepath),
             '-frames:v', '1', '-q:v', '5', str(out)],
            capture_output=True, timeout=15,
        )
        if out.exists() and out.stat().st_size > 0:
            import base64
            return base64.b64encode(out.read_bytes()).decode('ascii')
    except Exception:
        pass
    return None


# ─────────────────────────────────────────────────────────────────────────────
# File flagging
# ─────────────────────────────────────────────────────────────────────────────

def _flag_file(filepath: Path, min_size_bytes: int) -> Optional[str]:
    """Return a short flag string if the file has an issue, else None."""
    try:
        size = filepath.stat().st_size
    except OSError:
        return "unreadable"
    if size == 0:
        return "zero-byte"
    if filepath.suffix.lower() in VIDEO_EXTENSIONS and size < min_size_bytes:
        kb = size / 1024
        return f"small ({kb:.1f} KB)"
    return None


# ─────────────────────────────────────────────────────────────────────────────
# HTML templates
# ─────────────────────────────────────────────────────────────────────────────

_PAGE_TEMPLATE = Template("""\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>QC Report — $project_name</title>
<style>
  body { font-family: Arial, sans-serif; background: #1a1a2e; color: #e0e0e0; margin: 0; padding: 20px; }
  h1 { color: #c792ea; border-bottom: 2px solid #444; padding-bottom: 8px; }
  h2 { color: #82aaff; margin-top: 30px; }
  .summary { background: #16213e; border: 1px solid #444; border-radius: 6px; padding: 16px; margin-bottom: 24px; display: flex; gap: 32px; flex-wrap: wrap; }
  .stat { text-align: center; }
  .stat .value { font-size: 2em; font-weight: bold; color: #c3e88d; }
  .stat .label { font-size: 0.85em; color: #888; }
  table { width: 100%; border-collapse: collapse; background: #16213e; border-radius: 6px; overflow: hidden; }
  th { background: #0f3460; color: #c792ea; padding: 10px 12px; text-align: left; font-size: 0.85em; text-transform: uppercase; letter-spacing: 0.05em; }
  td { padding: 8px 12px; border-bottom: 1px solid #2a2a4a; font-size: 0.9em; vertical-align: middle; }
  tr:last-child td { border-bottom: none; }
  tr:nth-child(even) td { background: #1a1a3e; }
  .flag-ok  { color: #c3e88d; }
  .flag-bad { color: #ff5370; font-weight: bold; }
  .flag-warn{ color: #ffcb6b; }
  .thumb { max-width: 120px; max-height: 68px; border-radius: 3px; display: block; }
  .no-thumb { color: #555; font-size: 0.8em; }
  .generated { color: #555; font-size: 0.8em; margin-top: 40px; text-align: right; }
</style>
</head>
<body>
<h1>QC Report — $project_name</h1>
<div class="summary">
  <div class="stat"><div class="value">$total_files</div><div class="label">Total Files</div></div>
  <div class="stat"><div class="value">$total_size</div><div class="label">Total Size</div></div>
  <div class="stat"><div class="value $flag_color">$flagged_count</div><div class="label">Flagged</div></div>
  <div class="stat"><div class="value">$report_date</div><div class="label">Report Date</div></div>
</div>
<h2>File Listing</h2>
<table>
<thead>
<tr>
  <th>Thumbnail</th>
  <th>Filename</th>
  <th>Size</th>
  <th>Codec / Resolution</th>
  <th>Duration</th>
  <th>Status</th>
</tr>
</thead>
<tbody>
$rows
</tbody>
</table>
<p class="generated">Generated by Pearl's File Tools on $generated_at</p>
</body>
</html>
""")

_ROW_TEMPLATE = Template("""\
<tr>
  <td>$thumb_cell</td>
  <td>$filename<br><small style="color:#666">$rel_folder</small></td>
  <td>$size_str</td>
  <td>$media_str</td>
  <td>$duration_str</td>
  <td class="$flag_class">$flag_str</td>
</tr>
""")


# ─────────────────────────────────────────────────────────────────────────────
# Public API
# ─────────────────────────────────────────────────────────────────────────────

def _fmt_size(n: int) -> str:
    if n < 1024:
        return f"{n} B"
    if n < 1024 ** 2:
        return f"{n / 1024:.1f} KB"
    if n < 1024 ** 3:
        return f"{n / 1024 ** 2:.1f} MB"
    return f"{n / 1024 ** 3:.2f} GB"


def generate_qc_report(
    source_dir: Path,
    project_name: str,
    min_flag_size_bytes: int = 1024 * 1024,
    include_thumbnails: bool = True,
) -> Path:
    """Generate QC_Report_[YYYYMMDD_HHMMSS].html in *source_dir* and return its path."""
    from core.media_info import get_media_info

    ts = datetime.datetime.now().strftime('%Y%m%d_%H%M%S')
    out_path = source_dir / f"QC_Report_{ts}.html"

    all_files = sorted(fp for fp in source_dir.rglob('*') if fp.is_file())
    total_size = 0
    flagged_count = 0
    rows_html = []

    with tempfile.TemporaryDirectory() as tmp_str:
        tmp_dir = Path(tmp_str)

        for fp in all_files:
            try:
                stat = fp.stat()
                size = stat.st_size
            except OSError:
                size = 0
            total_size += size

            # Media info
            media_str = ''
            duration_str = ''
            try:
                info = get_media_info(fp)
                if info:
                    parts = []
                    if info.codec:
                        parts.append(info.codec)
                    if info.resolution_str:
                        parts.append(info.resolution_str)
                    if info.fps_str:
                        parts.append(f"{info.fps_str} fps")
                    media_str = ', '.join(parts)
                    if info.duration_str:
                        duration_str = info.duration_str
            except Exception:
                pass

            # Thumbnail
            thumb_cell = '<span class="no-thumb">—</span>'
            if include_thumbnails and _HAS_FFMPEG and fp.suffix.lower() in VIDEO_EXTENSIONS:
                b64 = _extract_thumbnail_b64(fp, tmp_dir)
                if b64:
                    thumb_cell = f'<img class="thumb" src="data:image/jpeg;base64,{b64}" alt="">'

            # Flag
            flag = _flag_file(fp, min_flag_size_bytes)
            if flag:
                flagged_count += 1
                flag_class = 'flag-bad'
                flag_str = flag
            else:
                flag_class = 'flag-ok'
                flag_str = 'OK'

            # Relative folder
            try:
                rel = str(fp.parent.relative_to(source_dir))
                rel_folder = '' if rel == '.' else rel
            except ValueError:
                rel_folder = ''

            rows_html.append(_ROW_TEMPLATE.substitute(
                thumb_cell=thumb_cell,
                filename=fp.name,
                rel_folder=rel_folder,
                size_str=_fmt_size(size),
                media_str=media_str or '—',
                duration_str=duration_str or '—',
                flag_class=flag_class,
                flag_str=flag_str,
            ))

    flag_color = 'flag-bad' if flagged_count > 0 else 'flag-ok'
    html = _PAGE_TEMPLATE.substitute(
        project_name=project_name,
        total_files=len(all_files),
        total_size=_fmt_size(total_size),
        flagged_count=flagged_count,
        flag_color=flag_color,
        report_date=datetime.date.today().isoformat(),
        generated_at=datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
        rows=''.join(rows_html),
    )

    out_path.write_text(html, encoding='utf-8')
    return out_path
